#!/bin/bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "staging" ] || [ "$branch" = "main" ]; then
    echo "You can't commit directly to $branch branch"
    exit 1
fi

echo "🔍 Running Pint in check mode..."
./vendor/bin/pint --test --dirty
STATUS=$?

if [ $STATUS -ne 0 ]; then
  echo "❌ Pint found formatting issues."
  echo "Run './vendor/bin/pint' to fix them before committing."
  exit 1
fi

exit 0

