language: en-US

reviews:
  profile: chill
  auto_review:
    enabled: true
    base_branches:
      - staging
  auto_apply_labels: false
  labeling_instructions: []

chat:
  auto_reply: true

issue_enrichment:
  auto_enrich:
    enabled: false
  labeling:
    auto_apply_labels: false
    labeling_instructions: []
