<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Balance Sheet — {{ $label }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; padding: 20px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
        .positive { color: #16a34a; }
        .negative { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { text-align: left; font-size: 10px; text-transform: uppercase; color: #666; padding: 6px 8px; border-bottom: 1px solid #ccc; }
        td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
        tr:last-child td { border-bottom: none; }
        .text-right { text-align: right; }
        .total-row td { font-weight: bold; border-top: 1px solid #ccc; border-bottom: none; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; }
    </style>
</head>
<body>

<h1>Balance Sheet — As of {{ $label }}</h1>
<div class="subtitle">Generated {{ now()->format('F j, Y') }}</div>

<h2>Account Balances</h2>
<table>
    <thead>
        <tr>
            <th>Account</th>
            <th class="text-right">Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($accounts as $ab)
        <tr>
            <td>{{ $ab['name'] }}</td>
            <td class="text-right {{ $ab['balance'] >= 0 ? 'positive' : 'negative' }}">
                ${{ number_format($ab['balance'] / 100, 2) }}
            </td>
        </tr>
        @endforeach
        <tr class="total-row">
            <td>Net Assets</td>
            <td class="text-right {{ $netAssets >= 0 ? 'positive' : 'negative' }}">
                ${{ number_format($netAssets / 100, 2) }}
            </td>
        </tr>
    </tbody>
</table>

<div class="footer">
    Generated by Lighthouse Finance System
</div>

</body>
</html>
