<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cash Flow Statement — {{ $label }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; padding: 20px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
        .positive { color: #16a34a; }
        .negative { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { text-align: left; font-size: 10px; text-transform: uppercase; color: #666; padding: 6px 8px; border-bottom: 1px solid #ccc; }
        td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
        tr:last-child td { border-bottom: none; }
        .text-right { text-align: right; }
        .total-row td { font-weight: bold; border-top: 1px solid #ccc; border-bottom: none; }
        .net-change { margin-top: 16px; text-align: right; font-size: 14px; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; }
    </style>
</head>
<body>

<h1>Cash Flow Statement — {{ $label }}</h1>
<div class="subtitle">Generated {{ now()->format('F j, Y') }}</div>

<h2>Operating Activities</h2>
<table>
    <thead>
        <tr>
            <th>Description</th>
            <th class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($cashFlow['income'] as $cat)
        <tr>
            <td>{{ $cat['name'] }} (income)</td>
            <td class="text-right positive">${{ number_format($cat['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
        @foreach ($cashFlow['expense'] as $cat)
        <tr>
            <td>{{ $cat['name'] }} (expense)</td>
            <td class="text-right negative">-${{ number_format($cat['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
        <tr class="total-row">
            <td>Net from Operations</td>
            <td class="text-right {{ $cashFlow['netOperating'] >= 0 ? 'positive' : 'negative' }}">
                {{ $cashFlow['netOperating'] >= 0 ? '+' : '' }}${{ number_format(abs($cashFlow['netOperating']) / 100, 2) }}
            </td>
        </tr>
    </tbody>
</table>

@if (!empty($cashFlow['transfers']))
<h2>Financing Activities (Transfers)</h2>
<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>From</th>
            <th>To</th>
            <th class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($cashFlow['transfers'] as $tx)
        <tr>
            <td>{{ $tx['date'] }}</td>
            <td>{{ $tx['from'] }}</td>
            <td>{{ $tx['to'] }}</td>
            <td class="text-right">${{ number_format($tx['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="net-change {{ $cashFlow['netChange'] >= 0 ? 'positive' : 'negative' }}">
    Net Cash Change: {{ $cashFlow['netChange'] >= 0 ? '+' : '' }}${{ number_format(abs($cashFlow['netChange']) / 100, 2) }}
</div>

<div class="footer">
    Generated by Lighthouse Finance System
</div>

</body>
</html>
