<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Income Statement — {{ $label }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; padding: 20px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
        .summary-grid { display: flex; gap: 20px; margin-bottom: 16px; }
        .summary-box { flex: 1; border: 1px solid #ddd; padding: 10px; border-radius: 4px; }
        .summary-box .label { font-size: 10px; color: #666; text-transform: uppercase; }
        .summary-box .value { font-size: 16px; font-weight: bold; margin-top: 4px; }
        .positive { color: #16a34a; }
        .negative { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { text-align: left; font-size: 10px; text-transform: uppercase; color: #666; padding: 6px 8px; border-bottom: 1px solid #ccc; }
        td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
        tr:last-child td { border-bottom: none; }
        .text-right { text-align: right; }
        .subcategory td { padding-left: 24px; color: #666; }
        .total-row td { font-weight: bold; border-top: 1px solid #ccc; border-bottom: none; }
        .net-income { margin-top: 16px; text-align: right; font-size: 14px; font-weight: bold; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; }
    </style>
</head>
<body>

<h1>Income Statement — {{ $label }}</h1>
<div class="subtitle">Generated {{ now()->format('F j, Y') }}</div>

<h2>Summary</h2>
<div class="summary-grid">
    <div class="summary-box">
        <div class="label">Total Income</div>
        <div class="value positive">${{ number_format($report['totalIncome'] / 100, 2) }}</div>
    </div>
    <div class="summary-box">
        <div class="label">Total Expenses</div>
        <div class="value negative">${{ number_format($report['totalExpense'] / 100, 2) }}</div>
    </div>
    <div class="summary-box">
        <div class="label">Net Income</div>
        <div class="value {{ $report['netIncome'] >= 0 ? 'positive' : 'negative' }}">
            {{ $report['netIncome'] >= 0 ? '+' : '' }}${{ number_format(abs($report['netIncome']) / 100, 2) }}
        </div>
    </div>
</div>

@if (!empty($report['income']))
<h2>Income</h2>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($report['income'] as $cat)
        <tr>
            <td>{{ $cat['name'] }}</td>
            <td class="text-right positive">${{ number_format($cat['total'] / 100, 2) }}</td>
        </tr>
        @foreach ($cat['subcategories'] as $sub)
        <tr class="subcategory">
            <td>{{ $sub['name'] }}</td>
            <td class="text-right">${{ number_format($sub['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
        @endforeach
        <tr class="total-row">
            <td>Total Income</td>
            <td class="text-right positive">${{ number_format($report['totalIncome'] / 100, 2) }}</td>
        </tr>
    </tbody>
</table>
@endif

@if (!empty($report['expense']))
<h2>Expenses</h2>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th class="text-right">Amount</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($report['expense'] as $cat)
        <tr>
            <td>{{ $cat['name'] }}</td>
            <td class="text-right negative">${{ number_format($cat['total'] / 100, 2) }}</td>
        </tr>
        @foreach ($cat['subcategories'] as $sub)
        <tr class="subcategory">
            <td>{{ $sub['name'] }}</td>
            <td class="text-right">${{ number_format($sub['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
        @endforeach
        <tr class="total-row">
            <td>Total Expenses</td>
            <td class="text-right negative">${{ number_format($report['totalExpense'] / 100, 2) }}</td>
        </tr>
    </tbody>
</table>
@endif

<div class="net-income {{ $report['netIncome'] >= 0 ? 'positive' : 'negative' }}">
    Net Income: {{ $report['netIncome'] >= 0 ? '+' : '' }}${{ number_format(abs($report['netIncome']) / 100, 2) }}
</div>

<div class="footer">
    Generated by Lighthouse Finance System
</div>

</body>
</html>
