<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Period Report — {{ $label }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; margin: 0; padding: 20px; }
        h1 { font-size: 20px; margin-bottom: 4px; }
        h2 { font-size: 14px; margin-top: 20px; margin-bottom: 6px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
        .subtitle { color: #666; font-size: 11px; margin-bottom: 20px; }
        .summary-grid { display: flex; gap: 20px; margin-bottom: 16px; }
        .summary-box { flex: 1; border: 1px solid #ddd; padding: 10px; border-radius: 4px; }
        .summary-box .label { font-size: 10px; color: #666; text-transform: uppercase; }
        .summary-box .value { font-size: 16px; font-weight: bold; margin-top: 4px; }
        .positive { color: #16a34a; }
        .negative { color: #dc2626; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th { text-align: left; font-size: 10px; text-transform: uppercase; color: #666; padding: 6px 8px; border-bottom: 1px solid #ccc; }
        td { padding: 6px 8px; border-bottom: 1px solid #f0f0f0; font-size: 11px; }
        tr:last-child td { border-bottom: none; }
        .text-right { text-align: right; }
        .footer { margin-top: 30px; font-size: 10px; color: #999; }
    </style>
</head>
<body>

<h1>Period Report — {{ $label }}</h1>
<div class="subtitle">Published {{ $publishedAt ? $publishedAt->format('F j, Y') : 'N/A' }}</div>

<h2>Summary</h2>
<div class="summary-grid">
    <div class="summary-box">
        <div class="label">Total Income</div>
        <div class="value positive">${{ number_format($summary['income'] / 100, 2) }}</div>
    </div>
    <div class="summary-box">
        <div class="label">Total Expenses</div>
        <div class="value negative">${{ number_format($summary['expense'] / 100, 2) }}</div>
    </div>
    <div class="summary-box">
        <div class="label">Net Change</div>
        <div class="value {{ $summary['net'] >= 0 ? 'positive' : 'negative' }}">
            {{ $summary['net'] >= 0 ? '+' : '' }}${{ number_format(abs($summary['net']) / 100, 2) }}
        </div>
    </div>
</div>

@if ($summary['accountBalances']->isNotEmpty())
<h2>Account Balances (as of end of period)</h2>
<table>
    <thead>
        <tr>
            <th>Account</th>
            <th class="text-right">Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($summary['accountBalances'] as $ab)
        <tr>
            <td>{{ $ab['name'] }}</td>
            <td class="text-right">${{ number_format($ab['balance'] / 100, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@if (!empty($summary['budgetVariances']))
<h2>Budget Variance by Category</h2>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th>Type</th>
            <th class="text-right">Planned</th>
            <th class="text-right">Actual</th>
            <th class="text-right">Variance</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($summary['budgetVariances'] as $bv)
        <tr>
            <td>{{ $bv['name'] }}</td>
            <td>{{ ucfirst($bv['type']) }}</td>
            <td class="text-right">{{ $bv['planned'] > 0 ? '$' . number_format($bv['planned'] / 100, 2) : '—' }}</td>
            <td class="text-right">{{ $bv['actual'] > 0 ? '$' . number_format($bv['actual'] / 100, 2) : '—' }}</td>
            <td class="text-right {{ $bv['variance'] >= 0 ? 'positive' : 'negative' }}">
                {{ $bv['variance'] >= 0 ? '+' : '' }}${{ number_format(abs($bv['variance']) / 100, 2) }}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@if (!empty($summary['incomeByCategory']) || !empty($summary['expenseByCategory']))
<h2>Transactions by Category</h2>
<table>
    <thead>
        <tr>
            <th>Category</th>
            <th>Type</th>
            <th class="text-right">Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($summary['incomeByCategory'] as $cat)
        <tr>
            <td>{{ $cat['name'] }}</td>
            <td>Income</td>
            <td class="text-right positive">${{ number_format($cat['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
        @foreach ($summary['expenseByCategory'] as $cat)
        <tr>
            <td>{{ $cat['name'] }}</td>
            <td>Expense</td>
            <td class="text-right negative">${{ number_format($cat['amount'] / 100, 2) }}</td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

<div class="footer">
    Generated by Lighthouse Finance System
</div>

</body>
</html>
