name: Deploy Notifier

on:
  push:
    branches: [staging, main]

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Post to Discord
        if: ${{ env.DISCORD_WEBHOOK != '' }}
        run: |
          branch="${GITHUB_REF_NAME}"
          short_sha="${GITHUB_SHA::7}"
          env_name=$([ "$branch" = "main" ] && echo "production" || echo "staging")
          msg="🚀 Deploy triggered to *$env_name* by ${GITHUB_ACTOR} (${branch} @ ${short_sha})"
          url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"

          curl -H "Content-Type: application/json" -X POST "$DISCORD_WEBHOOK" \
            -d "$(jq -n --arg t "$msg" --arg u "$url" '{content: ($t + "\n" + $u)}')"
